library(pivottabler)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()

library(pivottabler)
pt <- PivotTable$new()
pt$addData(mydata1)
#pt$addColumnDataGroups("EMP_NAME")
pt$addRowDataGroups("Project2")
pt$defineCalculation(calculationName="TotalEmp", summariseExpression="n()")
pt$renderPivot()